### ISSUE TITLE
In order to have access to Redshift the lamba will need to be in the VPC

### ISSUE THREAD

**Issue by danielsan** [EveryMundo/da-global-demand-sheets-updater#3]
Right after the last tag
https://github.com/EveryMundo/da-global-demand-sheets-updater/blob/8cef4ce2a0ae2c716f4aa235fa1928cdaa1a587a/serverless.yml#L26
but at the level of the tags key, under provider, you'll have to add the following
```yaml
  vpc:
    subnetIds:
      - subnet-b05fbed4
      - subnet-27ea0f51
      - subnet-7fa89926
    securityGroupIds:
      - sg-3c509e5b
      - sg-b232b8d5
```
